[package]
name = "lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
parser.workspace = true
syntax.workspace = true
locale.workspace = true
ide.workspace = true
anyhow.workspace = true
line-index.workspace = true
async-lsp.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_derive.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rgt.workspace = true
async-inc.workspace = true
