[package]
name = "lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
parser.workspace = true
syntax.workspace = true
locale.workspace = true
anyhow.workspace = true
line-index.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
serde.workspace = true
serde_derive.workspace = true
rgt.workspace = true
